### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by mmakmw** [PayU-EMEA/PayU-Flutter#1]
Hi, we're interested in integrating PayU in our Flutter app.

Since this repo was created only 10 days ago and is still empty, could you provide an estimate on when this Flutter plugin will be available to use?

Thanks you.

**Comment by aivashyna** [comment]
@mmakmw Hello. 

The package is now in `alpha` stage and is located on pre release branch. 
Here you can find more details about the integration process.
https://github.com/PayU-EMEA/PayU-Flutter/tree/release/0.0.1-alpha

Thank you.
